import Navbar from "./components/navbar"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from "react-hot-toast"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      <div className="dark:text-white h-[calc(100vh-5rem)] p-10">
        <div className="container mx-auto h-full">{children}</div>
      </div>
        {children}
      <Toaster/>
      </body>
    </html>
  )
}
